name: Armored
version: '${project.version}'
main: me.armored.core.Armored
api-version: 1.19

commands:
  ban:
    description: "Ban player"
    usage: /ban <player> <reason>
    permission: ranks.admin



  unban:
    description: "Unban player"
    usage: /unban <player>
    permission: ranks.admin


  b:
    description: enable/disable build mode
    usage: /build
    aliases: [ b, build ]
    permission: ranks.builder


permissions:
  ranks.admin:
    description: "admin"
    children:
      - ranks.builder

  ranks.builder:
    description: "builder"